apiVersion: apps/v1
kind: Deployment
metadata:
  name: osd-metrics-exporter
  namespace: clusters-l-4-10-hshift-25852
spec:
  replicas: 1
  selector:
    matchLabels:
      name: osd-metrics-exporter
  template:
    metadata:
      labels:
        name: osd-metrics-exporter
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
              weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      serviceAccountName: osd-metrics-exporter
      containers:
        - name: osd-metrics-exporter
          # Replace this with the built image name
          image: quay.io/app-sre/osd-metrics-exporter@0d725b91398ed3db11249808d89e688e62e511bbd4a2e875ed8493ce1febdb2c
          command:
            - osd-metrics-exporter
          imagePullPolicy: Always
          env:
            - name: KUBECONFIG
              value: /tmp/kubeconfig-l-4-10-hshift-25852 
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "osd-metrics-exporter"
