apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
    name: osd-metrics-exporter
policyDefaults:
    namespace: test-osd-policies
    placement:
        clusterSelectors:
            local-cluster: "true"
    remediationAction: enforce
policies:
  - name: osd-metrics-exporter-hcp
    manifests:
      - path: osd-metrics-exporter-hcp.yaml
  - name: osd-metrics-exporter-deployment
    manifests:
      - path: deployment.yaml
